"""Eliminación en cascada del tablero arreglado

Revision ID: 03b84822095a
Revises: 70c458ce0ed2
Create Date: 2025-09-11 15:48:55.401772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b84822095a'
down_revision = '70c458ce0ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_assignees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('card_assignees_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('card_assignees_card_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_assignees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('card_assignees_card_id_fkey'), 'cards', ['card_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('card_assignees_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
