"""Se añaden columnas nuevas y sus relaciones a los modelos card, board y list

Revision ID: 19951dee0733
Revises: 676de69b5f9e
Create Date: 2025-08-01 10:36:01.582894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19951dee0733'
down_revision = '676de69b5f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_assignee',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'user_id')
    )
    op.create_table('card_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card_assignees')
    op.drop_table('card_comments')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('card_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('card_comments_card_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('card_comments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('card_comments_pkey'))
    )
    op.create_table('card_assignees',
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('card_assignees_card_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('card_assignees_user_id_fkey')),
    sa.PrimaryKeyConstraint('card_id', 'user_id', name=op.f('card_assignees_pkey'))
    )
    op.drop_table('card_comment')
    op.drop_table('card_assignee')
    # ### end Alembic commands ###
