"""fix: se agrega columna card_title y se corrigen algunos valores

Revision ID: 24568b05b498
Revises: 385924beb55b
Create Date: 2025-09-25 23:30:18.738854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24568b05b498'
down_revision = '385924beb55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_title', sa.String(length=255), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('card_title')

    # ### end Alembic commands ###
