"""fix: Actualizacion del tablero de comentarios

Revision ID: 385924beb55b
Revises: e46df471f1cc
Create Date: 2025-09-23 12:34:38.904357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385924beb55b'
down_revision = 'e46df471f1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('READ', 'UNREAD', name='status'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('card_comments_card_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('card_comments_card_id_fkey'), 'cards', ['card_id'], ['id'])

    op.drop_table('notifications')
    # ### end Alembic commands ###
