"""Eliminacion de la columna color en las etiquetas de las cards

Revision ID: 398b1adb968f
Revises: e20ce9571abc
Create Date: 2025-08-26 12:43:26.110970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398b1adb968f'
down_revision = 'e20ce9571abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
