"""tags pertenecen a un board determinado

Revision ID: 3aac3b312885
Revises: fa1f03606127
Create Date: 2025-08-19 03:22:37.085592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aac3b312885'
down_revision = 'fa1f03606127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS card_tags CASCADE;")
    op.drop_table('board_tag')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_tag_per_board', ['name', 'board_id'])
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_tag_per_board', type_='unique')
        batch_op.drop_column('board_id')
        batch_op.drop_column('color')

    op.create_table('board_tag',
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('board_tag_board_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('board_tag_tag_id_fkey')),
    sa.PrimaryKeyConstraint('board_id', 'tag_id', name=op.f('board_tag_pkey'))
    )
    # ### end Alembic commands ###
