"""Añadimos relacion con etiquetas a las tablas

Revision ID: 676de69b5f9e
Revises: 84c6d5435ad5
Create Date: 2025-07-24 10:03:44.916959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676de69b5f9e'
down_revision = '84c6d5435ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('board_tag',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('board_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
