"""Eliminación en cascada de las listas

Revision ID: 70c458ce0ed2
Revises: c23727228664
Create Date: 2025-09-11 15:40:32.016265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c458ce0ed2'
down_revision = 'c23727228664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cards_list_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lists', ['list_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cards_list_id_fkey'), 'lists', ['list_id'], ['id'])

    # ### end Alembic commands ###
