"""empty message

Revision ID: 84c6d5435ad5
Revises: e1c77a74a5e4
Create Date: 2025-07-23 10:54:33.230693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c6d5435ad5'
down_revision = 'e1c77a74a5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    board_status_enum = sa.Enum('PUBLIC', 'PRIVATE', name='board_status')
    board_status_enum.create(op.get_bind())
    op.create_table('user_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('board_members')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_image_url', sa.String(length=360), nullable=True))
        batch_op.add_column(sa.Column('status', board_status_enum, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    board_status_enum = sa.Enum('PUBLIC', 'PRIVATE', name='board_status')
    board_status_enum.drop(op.get_bind())
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('board_image_url')

    op.create_table('board_members',
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('board_members_board_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('board_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('board_id', 'user_id', name=op.f('board_members_pkey'))
    )
    op.drop_table('user_board')
    # ### end Alembic commands ###
