"""actualización de la tabla de card

Revision ID: b4bb16c3d3b7
Revises: 3f4fa0a7e47b
Create Date: 2025-08-15 03:07:16.153509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4bb16c3d3b7'
down_revision = '3f4fa0a7e47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_assignees',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'user_id')
    )
    op.create_table('card_tag',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'tag_id')
    )
    op.drop_table('card_comment')
    op.drop_table('card_assignee')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reminder_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_message', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('board_id')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('reminder_message')
        batch_op.drop_column('reminder_date')
        batch_op.drop_column('status')
        batch_op.drop_column('priority')
        batch_op.drop_column('due_date')

    op.create_table('card_assignee',
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('card_assignee_card_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('card_assignee_user_id_fkey')),
    sa.PrimaryKeyConstraint('card_id', 'user_id', name=op.f('card_assignee_pkey'))
    )
    op.create_table('card_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('card_comment_card_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('card_comment_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('card_comment_pkey'))
    )
    op.drop_table('card_tag')
    op.drop_table('card_assignees')
    # ### end Alembic commands ###
