"""Eliminación en cascada del tablero

Revision ID: c23727228664
Revises: 3240324182a4
Create Date: 2025-09-11 15:31:04.358317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23727228664'
down_revision = '3240324182a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('board_tag_tag_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('board_tag_board_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('card_tags_board_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('card_tags_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('card_tags_assoc_tag_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('card_tags_assoc_card_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'card_tags', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lists_board_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lists_board_id_fkey'), 'boards', ['board_id'], ['id'])

    with op.batch_alter_table('card_tags_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('card_tags_assoc_card_id_fkey'), 'cards', ['card_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('card_tags_assoc_tag_id_fkey'), 'card_tags', ['tag_id'], ['id'])

    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('card_tags_board_id_fkey'), 'boards', ['board_id'], ['id'])

    with op.batch_alter_table('board_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('board_tag_board_id_fkey'), 'boards', ['board_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('board_tag_tag_id_fkey'), 'tags', ['tag_id'], ['id'])

    # ### end Alembic commands ###
