"""Cambio de nombres a la relacion de las cards con sus tarjetas

Revision ID: cc2b2c06b8e8
Revises: 398b1adb968f
Create Date: 2025-08-26 12:53:29.437051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2b2c06b8e8'
down_revision = '398b1adb968f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_tags_assoc',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['card_tags.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'tag_id')
    )
    op.drop_table('card_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_tag',
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('card_tag_card_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['card_tags.id'], name=op.f('card_tag_tag_id_fkey')),
    sa.PrimaryKeyConstraint('card_id', 'tag_id', name=op.f('card_tag_pkey'))
    )
    op.drop_table('card_tags_assoc')
    # ### end Alembic commands ###
