"""Relaciones con las tags de las cards arregladas

Revision ID: e20ce9571abc
Revises: 3aac3b312885
Create Date: 2025-08-22 15:45:18.856976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20ce9571abc'
down_revision = '3aac3b312885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_tag',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('board_id', 'tag_id')
    )
    op.create_table('card_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'board_id', name='unique_cardtag_per_board')
    )
    with op.batch_alter_table('card_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('card_tag_tag_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'card_tags', ['tag_id'], ['id'])

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_tag_per_board'), type_='unique')
        batch_op.drop_constraint(batch_op.f('tags_board_id_fkey'), type_='foreignkey')
        batch_op.drop_column('color')
        batch_op.drop_column('board_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('tags_board_id_fkey'), 'boards', ['board_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('unique_tag_per_board'), ['name', 'board_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('card_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('card_tag_tag_id_fkey'), 'tags', ['tag_id'], ['id'])

    op.drop_table('card_tags')
    op.drop_table('board_tag')
    # ### end Alembic commands ###
